paper:
  width: 180
  height: 150
  margin: 0
label:
  width: 60
  height: 20
  type:
    width: 8
    font_size: 7
    margin_correction: 0.9
  subtype:
    width: 5.5
    font_size: 4
    margin_correction: 0.5
  name:
    font_size: 7.5
    margin_correction: 1
types:
  PETG:
    label: "PETG"
    color: [ 0, 200, 0 ]
  PLA:
    label: "PLA"
    color: [ 0, 0, 250 ]
  TPU:
    label: "TPU"
    color: [ 252, 186, 3 ]
  ABS:
    label: "ABS"
    color: [ 200, 0, 0 ]
  ASA:
    label: "ASA"
    color: [ 252, 117, 20 ]
